language: perl

perl: ["5.22", "5.24", "5.26"]

install:
  - "cpanm -n Devel::Cover Test::Pod Test::Pod::Coverage Devel::Cover::Report::Coveralls"
  - "cpanm -n --quiet --installdeps ."
  - "cpanm https://github.com/kiwiroy/fatpack-maint-builder/releases/download/v1.1/FatPack-Maint-Build-1.1.tar.gz"

after_success: "cover -test -report coveralls"

notifications:
  email: false
