language: perl

perl: ["5.22", "5.24", "5.26"]

install:
  - "cpanm -n Devel::Cover Test::Pod Test::Pod::Coverage"
  - "cpanm -n --quiet --installdeps --with-develop ."

after_success: "cover -test -report coveralls"

notifications:
  email: false
